name: instagram_private_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0

environment:
  sdk: '>=2.2.2 <3.0.0'


dependencies:
  uuid: ^3.0.6
  json_annotation: ^4.5.0
  cookie_jar: ^3.0.1
  dio: ^4.0.6
  crypto: ^3.0.2
  hex: ^0.2.0
  image: ^3.2.0
  intl: ^0.17.0
  meta: ^1.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.21.2
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
